#!/bin/sh
if [ -z $JETPACK ]; then
	echo "JETPACK not set"
	exit
fi
KERNEL_SOURCES=${JETPACK}/source/public/kernel
TEGRA_KERNEL_OUT=${JETPACK}/source/kernel_build/jetson_linux_35.6.0_image
TOOLCHAIN_PREFIX=`pwd`/l4t-gcc/bin/aarch64-buildroot-linux-gnu-

make -C ${KERNEL_SOURCES}/kernel-5.10/ ARCH=arm64 O=${TEGRA_KERNEL_OUT} LOCALVERSION=-tegra CROSS_COMPILE=${TOOLCHAIN_PREFIX} mrproper
cp aventadorII.config ${KERNEL_SOURCES}/kernel-5.10/arch/arm64/configs/defconfig
make -C ${KERNEL_SOURCES}/kernel-5.10/ ARCH=arm64 O=${TEGRA_KERNEL_OUT} LOCALVERSION=-tegra CROSS_COMPILE=${TOOLCHAIN_PREFIX} tegra_defconfig
make -C ${KERNEL_SOURCES}/kernel-5.10/ ARCH=arm64 O=${TEGRA_KERNEL_OUT} LOCALVERSION=-tegra CROSS_COMPILE=${TOOLCHAIN_PREFIX} xconfig

